# syntax=docker/dockerfile:1

# For config options, see the README at: https://github.com/devcontainers/templates/tree/main/src/typescript-node
FROM mcr.microsoft.com/devcontainers/typescript-node:4.0.10-24-trixie

USER node:node

RUN curl -fsSL https://vite.plus | bash
