/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as SysIndexRouteImport } from "./routes/sys/index";
import { Route as SkillsIndexRouteImport } from "./routes/skills/index";
import { Route as ProjectsIndexRouteImport } from "./routes/projects/index";
import { Route as LinkIndexRouteImport } from "./routes/link/index";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const SysIndexRoute = SysIndexRouteImport.update({
  id: "/sys/",
  path: "/sys/",
  getParentRoute: () => rootRouteImport,
} as any);
const SkillsIndexRoute = SkillsIndexRouteImport.update({
  id: "/skills/",
  path: "/skills/",
  getParentRoute: () => rootRouteImport,
} as any);
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: "/projects/",
  path: "/projects/",
  getParentRoute: () => rootRouteImport,
} as any);
const LinkIndexRoute = LinkIndexRouteImport.update({
  id: "/link/",
  path: "/link/",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/link": typeof LinkIndexRoute;
  "/projects": typeof ProjectsIndexRoute;
  "/skills": typeof SkillsIndexRoute;
  "/sys": typeof SysIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/link": typeof LinkIndexRoute;
  "/projects": typeof ProjectsIndexRoute;
  "/skills": typeof SkillsIndexRoute;
  "/sys": typeof SysIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/link/": typeof LinkIndexRoute;
  "/projects/": typeof ProjectsIndexRoute;
  "/skills/": typeof SkillsIndexRoute;
  "/sys/": typeof SysIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/link" | "/projects" | "/skills" | "/sys";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/link" | "/projects" | "/skills" | "/sys";
  id: "__root__" | "/" | "/link/" | "/projects/" | "/skills/" | "/sys/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  LinkIndexRoute: typeof LinkIndexRoute;
  ProjectsIndexRoute: typeof ProjectsIndexRoute;
  SkillsIndexRoute: typeof SkillsIndexRoute;
  SysIndexRoute: typeof SysIndexRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/sys/": {
      id: "/sys/";
      path: "/sys";
      fullPath: "/sys";
      preLoaderRoute: typeof SysIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/skills/": {
      id: "/skills/";
      path: "/skills";
      fullPath: "/skills";
      preLoaderRoute: typeof SkillsIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/projects/": {
      id: "/projects/";
      path: "/projects";
      fullPath: "/projects";
      preLoaderRoute: typeof ProjectsIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/link/": {
      id: "/link/";
      path: "/link";
      fullPath: "/link";
      preLoaderRoute: typeof LinkIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LinkIndexRoute: LinkIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  SkillsIndexRoute: SkillsIndexRoute,
  SysIndexRoute: SysIndexRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { createStart } from "@tanstack/react-start";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
