name: Next.js Bundle Analysis

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ci-analysis-${{ github.head_ref || github.ref_name }}-anaylysis
  cancel-in-progress: true

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Setup TURBOREPO cache server
        uses: dtinth/setup-github-actions-caching-for-turbo@v1

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js v18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Cache Next.js
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**/*.ts', '**/*.tsx') }}
          restore-keys: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build website
        run: yarn build

      - name: Download base branch bundle stats
        uses: dawidd6/action-download-artifact@v2
        if: success() && github.event.number
        with:
          workflow: analysis.yml
          workflow_conclusion:
          branch: ${{ github.event.pull_request.base.ref }}
          path: .

      - name: Generate comment body
        uses: actions/github-script@v6
        if: success()
        id: bundle-results
        with:
          result-encoding: string
          script: |
            require('.pnp.cjs').setup();
            const script = require('.github/scripts/nextjs.js')
            await script({core})

      - name: Upload bundle
        uses: actions/upload-artifact@v3
        if: success()
        with:
          name: analysis
          path: analysis.json

      - name: Add comment to PR
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event.number
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ github.event.number }}
          header: bundle
          message: |
            ${{ steps.bundle-results.outputs.body }}
