name: Next.js Bundle Analysis

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ci-analysis-${{ github.head_ref || github.ref_name }}-
  cancel-in-progress: true

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache Next.js
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-nextjs-

      - name: Setup Node.js v16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Analyze bundle
        run: npx -p nextjs-bundle-analysis report

      - name: Upload bundle
        uses: actions/upload-artifact@v3
        with:
          name: bundle
          path: .next/analyze/__bundle_analysis.json

      - name: Download base branch bundle stats
        uses: dawidd6/action-download-artifact@v2
        if: success() && github.event.number
        with:
          workflow: ${{ github.event.pull_request.base.ref == 'main' && 'analysis.yml' }}
          branch: ${{ github.event.pull_request.base.ref }}
          path: .next/analyze/base

      - name: Compare with base branch bundle
        if: success() && github.event.number
        run: ls -laR .next/analyze/base && npx -p nextjs-bundle-analysis compare

      - name: Get comment body
        uses: actions/github-script@v6
        id: get-comment-body
        if: success() && github.event.number
        with:
          result-encoding: string
          script: |
            const { readFileSync } = require('fs')
            const comment = readFileSync('.next/analyze/__bundle_analysis_comment.txt', 'utf8')
            core.setOutput('body', comment)

      - name: Create Comment
        uses: peter-evans/create-or-update-comment@v2
        if: success() && github.event.number
        with:
          issue-number: ${{ github.event.number }}
          body: ${{ steps.get-comment-body.outputs.body }}
