name: Deploy Website

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
  delete:

concurrency:
  group: ci-deploy-${{ github.head_ref || github.ref_name }}-${{github.event_name}}
  cancel-in-progress: true

permissions:
  contents: read
  deployments: write

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Setup TURBOREPO cache server
        uses: dtinth/setup-github-actions-caching-for-turbo@v1

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js v18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Cache Next.js
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**/*.ts', '**/*.tsx') }}
          restore-keys: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build website
        run: yarn build
        env:
          BRANCH: '${{ github.ref }}'
          CF_SITE_KEY: '${{ secrets.CF_SITE_KEY }}'

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT }}
          projectName: website
          directory: out
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          wranglerVersion: '3'

  clean:
    name: Clean Deployments
    needs: deploy
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Destroy old deployments
        uses: eve0415/cf-pages-clean-deployments-action@pr-1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT }}
          projectName: website
