name: Check Format

on:
  pull_request:

concurrency:
  group: ci-format-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Setup TURBOREPO cache server
        uses: dtinth/setup-github-actions-caching-for-turbo@v1

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup yarn
        run: corepack enable yarn

      - name: Setup Node.js v20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: Cache Next.js
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**/*.ts', '**/*.tsx') }}
          restore-keys: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn install --immutable

      - name: Check code format with eslint and prettier
        run: yarn turbo lint:ci
